// Add near the top of src-tauri/src/main.rs:
mod recipe_runtime;

// Add inside tauri::generate_handler![ ... ]:
recipe_runtime::commands::recipe_list_apps,
recipe_runtime::commands::recipe_get_status,
recipe_runtime::commands::recipe_get_install_plan,
recipe_runtime::commands::recipe_run_resource_preflight,
recipe_runtime::commands::recipe_resolve_ports,
recipe_runtime::commands::recipe_accept_install_plan,
recipe_runtime::commands::recipe_clear_install_plan_acceptance,
recipe_runtime::commands::recipe_check_environment,
recipe_runtime::commands::recipe_install,
recipe_runtime::commands::recipe_start,
recipe_runtime::commands::recipe_stop,
recipe_runtime::commands::recipe_restart,
recipe_runtime::commands::recipe_open_dashboard,
recipe_runtime::commands::recipe_check_health,
recipe_runtime::commands::recipe_check_readiness,
recipe_runtime::commands::recipe_read_logs,
recipe_runtime::commands::recipe_run_doctor,
recipe_runtime::commands::recipe_run_onboarding,
recipe_runtime::commands::recipe_repair,
recipe_runtime::commands::recipe_save_secrets,
recipe_runtime::commands::recipe_rollback_failed_install,
recipe_runtime::commands::recipe_uninstall,
recipe_runtime::commands::recipe_import_user_recipe,
recipe_runtime::commands::recipe_remove_user_recipe,
recipe_runtime::commands::recipe_fetch_marketplace,
recipe_runtime::commands::recipe_get_runtime_error,
recipe_runtime::commands::recipe_retry_runtime_error,
recipe_runtime::commands::recipe_repair_runtime_error,
recipe_runtime::commands::recipe_check_gateway_status,
recipe_runtime::commands::recipe_check_runtime_status,
